// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/pubsub.proto

package pubsubproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_v1_pubsub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Topic) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicRequest) Reset() {
	*x = GetTopicRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicRequest) ProtoMessage() {}

func (x *GetTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicRequest.ProtoReflect.Descriptor instead.
func (*GetTopicRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         *Topic                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicResponse) Reset() {
	*x = GetTopicResponse{}
	mi := &file_v1_pubsub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicResponse) ProtoMessage() {}

func (x *GetTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicResponse.ProtoReflect.Descriptor instead.
func (*GetTopicResponse) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopicResponse) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

type UpdateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=newName,proto3" json:"newName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicRequest) Reset() {
	*x = UpdateTopicRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicRequest) ProtoMessage() {}

func (x *UpdateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicRequest.ProtoReflect.Descriptor instead.
func (*UpdateTopicRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTopicRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type UpdateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         *Topic                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicResponse) Reset() {
	*x = UpdateTopicResponse{}
	mi := &file_v1_pubsub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicResponse) ProtoMessage() {}

func (x *UpdateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicResponse.ProtoReflect.Descriptor instead.
func (*UpdateTopicResponse) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTopicResponse) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

type DeleteTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicRequest) Reset() {
	*x = DeleteTopicRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicRequest) ProtoMessage() {}

func (x *DeleteTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicRequest.ProtoReflect.Descriptor instead.
func (*DeleteTopicRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicResponse) Reset() {
	*x = DeleteTopicResponse{}
	mi := &file_v1_pubsub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicResponse) ProtoMessage() {}

func (x *DeleteTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicResponse.ProtoReflect.Descriptor instead.
func (*DeleteTopicResponse) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTopicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{8}
}

type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_v1_pubsub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{9}
}

func (x *ListTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	AutoExtend    bool                   `protobuf:"varint,3,opt,name=autoExtend,proto3" json:"autoExtend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_v1_pubsub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{10}
}

func (x *Subscription) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subscription) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Subscription) GetAutoExtend() bool {
	if x != nil {
		return x.AutoExtend
	}
	return false
}

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NoAutoExtend  bool                   `protobuf:"varint,3,opt,name=noAutoExtend,proto3" json:"noAutoExtend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSubscriptionRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetNoAutoExtend() bool {
	if x != nil {
		return x.NoAutoExtend
	}
	return false
}

type GetSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{12}
}

func (x *GetSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionResponse) Reset() {
	*x = GetSubscriptionResponse{}
	mi := &file_v1_pubsub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionResponse) ProtoMessage() {}

func (x *GetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{13}
}

func (x *GetSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type UpdateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NoAutoExtend  bool                   `protobuf:"varint,2,opt,name=noAutoExtend,proto3" json:"noAutoExtend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubscriptionRequest) Reset() {
	*x = UpdateSubscriptionRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionRequest) ProtoMessage() {}

func (x *UpdateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetNoAutoExtend() bool {
	if x != nil {
		return x.NoAutoExtend
	}
	return false
}

type UpdateSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubscriptionResponse) Reset() {
	*x = UpdateSubscriptionResponse{}
	mi := &file_v1_pubsub_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionResponse) ProtoMessage() {}

func (x *UpdateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type DeleteSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{17}
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_v1_pubsub_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{18}
}

func (x *ListSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_v1_pubsub_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{19}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type PublishRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Topic   string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional attributes for the message
	Attributes    map[string]string `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{20}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *PublishRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_v1_pubsub_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{21}
}

func (x *PublishResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  string                 `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{22}
}

func (x *SubscribeRequest) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type AcknowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  string                 `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeRequest) Reset() {
	*x = AcknowledgeRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeRequest) ProtoMessage() {}

func (x *AcknowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{23}
}

func (x *AcknowledgeRequest) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *AcknowledgeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AcknowledgeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type ExtendVisibilityTimeoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subscription  string                 `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendVisibilityTimeoutRequest) Reset() {
	*x = ExtendVisibilityTimeoutRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendVisibilityTimeoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendVisibilityTimeoutRequest) ProtoMessage() {}

func (x *ExtendVisibilityTimeoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendVisibilityTimeoutRequest.ProtoReflect.Descriptor instead.
func (*ExtendVisibilityTimeoutRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{24}
}

func (x *ExtendVisibilityTimeoutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExtendVisibilityTimeoutRequest) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *ExtendVisibilityTimeoutRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GetMessagesInQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`               // Filter by topic
	Subscription  string                 `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"` // Filter by subscription
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesInQueueRequest) Reset() {
	*x = GetMessagesInQueueRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesInQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesInQueueRequest) ProtoMessage() {}

func (x *GetMessagesInQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesInQueueRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesInQueueRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{25}
}

func (x *GetMessagesInQueueRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetMessagesInQueueRequest) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

type GetMessagesInQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InQueue       []*InQueue             `protobuf:"bytes,1,rep,name=inQueue,proto3" json:"inQueue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesInQueueResponse) Reset() {
	*x = GetMessagesInQueueResponse{}
	mi := &file_v1_pubsub_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesInQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesInQueueResponse) ProtoMessage() {}

func (x *GetMessagesInQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesInQueueResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesInQueueResponse) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{26}
}

func (x *GetMessagesInQueueResponse) GetInQueue() []*InQueue {
	if x != nil {
		return x.InQueue
	}
	return nil
}

type InQueue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  string                 `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InQueue) Reset() {
	*x = InQueue{}
	mi := &file_v1_pubsub_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InQueue) ProtoMessage() {}

func (x *InQueue) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InQueue.ProtoReflect.Descriptor instead.
func (*InQueue) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{27}
}

func (x *InQueue) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *InQueue) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RequeueMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Message Id
	Subscription  string                 `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequeueMessageRequest) Reset() {
	*x = RequeueMessageRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequeueMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequeueMessageRequest) ProtoMessage() {}

func (x *RequeueMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequeueMessageRequest.ProtoReflect.Descriptor instead.
func (*RequeueMessageRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{28}
}

func (x *RequeueMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequeueMessageRequest) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *RequeueMessageRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type PurgeTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"` // Topic to purge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeTopicRequest) Reset() {
	*x = PurgeTopicRequest{}
	mi := &file_v1_pubsub_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeTopicRequest) ProtoMessage() {}

func (x *PurgeTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeTopicRequest.ProtoReflect.Descriptor instead.
func (*PurgeTopicRequest) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{29}
}

func (x *PurgeTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type PurgeTopicResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NumMessagesPurged int32                  `protobuf:"varint,1,opt,name=numMessagesPurged,proto3" json:"numMessagesPurged,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PurgeTopicResponse) Reset() {
	*x = PurgeTopicResponse{}
	mi := &file_v1_pubsub_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeTopicResponse) ProtoMessage() {}

func (x *PurgeTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeTopicResponse.ProtoReflect.Descriptor instead.
func (*PurgeTopicResponse) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{30}
}

func (x *PurgeTopicResponse) GetNumMessagesPurged() int32 {
	if x != nil {
		return x.NumMessagesPurged
	}
	return 0
}

type HashDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Subscription  string                 `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashDetails) Reset() {
	*x = HashDetails{}
	mi := &file_v1_pubsub_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashDetails) ProtoMessage() {}

func (x *HashDetails) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashDetails.ProtoReflect.Descriptor instead.
func (*HashDetails) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{31}
}

func (x *HashDetails) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *HashDetails) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

type ListHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []*HashDetails         `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHashResponse) Reset() {
	*x = ListHashResponse{}
	mi := &file_v1_pubsub_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHashResponse) ProtoMessage() {}

func (x *ListHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pubsub_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHashResponse.ProtoReflect.Descriptor instead.
func (*ListHashResponse) Descriptor() ([]byte, []int) {
	return file_v1_pubsub_proto_rawDescGZIP(), []int{32}
}

func (x *ListHashResponse) GetHashes() []*HashDetails {
	if x != nil {
		return x.Hashes
	}
	return nil
}

var File_v1_pubsub_proto protoreflect.FileDescriptor

const file_v1_pubsub_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/pubsub.proto\x12\vpubsubproto\x1a\x1bgoogle/protobuf/empty.proto\"W\n" +
	"\x05Topic\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\tR\tupdatedAt\"(\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"%\n" +
	"\x0fGetTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"<\n" +
	"\x10GetTopicResponse\x12(\n" +
	"\x05topic\x18\x01 \x01(\v2\x12.pubsubproto.TopicR\x05topic\"B\n" +
	"\x12UpdateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\anewName\x18\x02 \x01(\tR\anewName\"?\n" +
	"\x13UpdateTopicResponse\x12(\n" +
	"\x05topic\x18\x01 \x01(\v2\x12.pubsubproto.TopicR\x05topic\"(\n" +
	"\x12DeleteTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x13DeleteTopicResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x13\n" +
	"\x11ListTopicsRequest\"@\n" +
	"\x12ListTopicsResponse\x12*\n" +
	"\x06topics\x18\x01 \x03(\v2\x12.pubsubproto.TopicR\x06topics\"X\n" +
	"\fSubscription\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"autoExtend\x18\x03 \x01(\bR\n" +
	"autoExtend\"i\n" +
	"\x19CreateSubscriptionRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fnoAutoExtend\x18\x03 \x01(\bR\fnoAutoExtend\",\n" +
	"\x16GetSubscriptionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"X\n" +
	"\x17GetSubscriptionResponse\x12=\n" +
	"\fsubscription\x18\x01 \x01(\v2\x19.pubsubproto.SubscriptionR\fsubscription\"S\n" +
	"\x19UpdateSubscriptionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fnoAutoExtend\x18\x02 \x01(\bR\fnoAutoExtend\"[\n" +
	"\x1aUpdateSubscriptionResponse\x12=\n" +
	"\fsubscription\x18\x01 \x01(\v2\x19.pubsubproto.SubscriptionR\fsubscription\"/\n" +
	"\x19DeleteSubscriptionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1a\n" +
	"\x18ListSubscriptionsRequest\"\\\n" +
	"\x19ListSubscriptionsResponse\x12?\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x19.pubsubproto.SubscriptionR\rsubscriptions\"\xce\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12D\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2$.pubsubproto.Message.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x01\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12K\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2+.pubsubproto.PublishRequest.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x0fPublishResponse\x12\x1c\n" +
	"\tmessageId\x18\x01 \x01(\tR\tmessageId\"L\n" +
	"\x10SubscribeRequest\x12\"\n" +
	"\fsubscription\x18\x01 \x01(\tR\fsubscription\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"^\n" +
	"\x12AcknowledgeRequest\x12\"\n" +
	"\fsubscription\x18\x01 \x01(\tR\fsubscription\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\"j\n" +
	"\x1eExtendVisibilityTimeoutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fsubscription\x18\x02 \x01(\tR\fsubscription\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\"U\n" +
	"\x19GetMessagesInQueueRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\"\n" +
	"\fsubscription\x18\x02 \x01(\tR\fsubscription\"L\n" +
	"\x1aGetMessagesInQueueResponse\x12.\n" +
	"\ainQueue\x18\x01 \x03(\v2\x14.pubsubproto.InQueueR\ainQueue\"C\n" +
	"\aInQueue\x12\"\n" +
	"\fsubscription\x18\x01 \x01(\tR\fsubscription\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"a\n" +
	"\x15RequeueMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fsubscription\x18\x02 \x01(\tR\fsubscription\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\")\n" +
	"\x11PurgeTopicRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"B\n" +
	"\x12PurgeTopicResponse\x12,\n" +
	"\x11numMessagesPurged\x18\x01 \x01(\x05R\x11numMessagesPurged\"E\n" +
	"\vHashDetails\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\"\n" +
	"\fsubscription\x18\x02 \x01(\tR\fsubscription\"D\n" +
	"\x10ListHashResponse\x120\n" +
	"\x06hashes\x18\x01 \x03(\v2\x18.pubsubproto.HashDetailsR\x06hashes2\xfb\v\n" +
	"\rPubSubService\x12H\n" +
	"\vCreateTopic\x12\x1f.pubsubproto.CreateTopicRequest\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\bGetTopic\x12\x1c.pubsubproto.GetTopicRequest\x1a\x1d.pubsubproto.GetTopicResponse\"\x00\x12R\n" +
	"\vUpdateTopic\x12\x1f.pubsubproto.UpdateTopicRequest\x1a .pubsubproto.UpdateTopicResponse\"\x00\x12H\n" +
	"\vDeleteTopic\x12\x1f.pubsubproto.DeleteTopicRequest\x1a\x16.google.protobuf.Empty\"\x00\x12O\n" +
	"\n" +
	"ListTopics\x12\x1e.pubsubproto.ListTopicsRequest\x1a\x1f.pubsubproto.ListTopicsResponse\"\x00\x12V\n" +
	"\x12CreateSubscription\x12&.pubsubproto.CreateSubscriptionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12^\n" +
	"\x0fGetSubscription\x12#.pubsubproto.GetSubscriptionRequest\x1a$.pubsubproto.GetSubscriptionResponse\"\x00\x12g\n" +
	"\x12UpdateSubscription\x12&.pubsubproto.UpdateSubscriptionRequest\x1a'.pubsubproto.UpdateSubscriptionResponse\"\x00\x12V\n" +
	"\x12DeleteSubscription\x12&.pubsubproto.DeleteSubscriptionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12d\n" +
	"\x11ListSubscriptions\x12%.pubsubproto.ListSubscriptionsRequest\x1a&.pubsubproto.ListSubscriptionsResponse\"\x00\x12F\n" +
	"\aPublish\x12\x1b.pubsubproto.PublishRequest\x1a\x1c.pubsubproto.PublishResponse\"\x00\x12D\n" +
	"\tSubscribe\x12\x1d.pubsubproto.SubscribeRequest\x1a\x14.pubsubproto.Message\"\x000\x01\x12H\n" +
	"\vAcknowledge\x12\x1f.pubsubproto.AcknowledgeRequest\x1a\x16.google.protobuf.Empty\"\x00\x12`\n" +
	"\x17ExtendVisibilityTimeout\x12+.pubsubproto.ExtendVisibilityTimeoutRequest\x1a\x16.google.protobuf.Empty\"\x00\x12g\n" +
	"\x12GetMessagesInQueue\x12&.pubsubproto.GetMessagesInQueueRequest\x1a'.pubsubproto.GetMessagesInQueueResponse\"\x00\x12N\n" +
	"\x0eRequeueMessage\x12\".pubsubproto.RequeueMessageRequest\x1a\x16.google.protobuf.Empty\"\x00\x12O\n" +
	"\n" +
	"PurgeTopic\x12\x1e.pubsubproto.PurgeTopicRequest\x1a\x1f.pubsubproto.PurgeTopicResponse\"\x00\x12C\n" +
	"\bListHash\x12\x16.google.protobuf.Empty\x1a\x1d.pubsubproto.ListHashResponse\"\x00B$Z\"github.com/alphauslabs/pubsubprotob\x06proto3"

var (
	file_v1_pubsub_proto_rawDescOnce sync.Once
	file_v1_pubsub_proto_rawDescData []byte
)

func file_v1_pubsub_proto_rawDescGZIP() []byte {
	file_v1_pubsub_proto_rawDescOnce.Do(func() {
		file_v1_pubsub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_pubsub_proto_rawDesc), len(file_v1_pubsub_proto_rawDesc)))
	})
	return file_v1_pubsub_proto_rawDescData
}

var file_v1_pubsub_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_v1_pubsub_proto_goTypes = []any{
	(*Topic)(nil),                          // 0: pubsubproto.Topic
	(*CreateTopicRequest)(nil),             // 1: pubsubproto.CreateTopicRequest
	(*GetTopicRequest)(nil),                // 2: pubsubproto.GetTopicRequest
	(*GetTopicResponse)(nil),               // 3: pubsubproto.GetTopicResponse
	(*UpdateTopicRequest)(nil),             // 4: pubsubproto.UpdateTopicRequest
	(*UpdateTopicResponse)(nil),            // 5: pubsubproto.UpdateTopicResponse
	(*DeleteTopicRequest)(nil),             // 6: pubsubproto.DeleteTopicRequest
	(*DeleteTopicResponse)(nil),            // 7: pubsubproto.DeleteTopicResponse
	(*ListTopicsRequest)(nil),              // 8: pubsubproto.ListTopicsRequest
	(*ListTopicsResponse)(nil),             // 9: pubsubproto.ListTopicsResponse
	(*Subscription)(nil),                   // 10: pubsubproto.Subscription
	(*CreateSubscriptionRequest)(nil),      // 11: pubsubproto.CreateSubscriptionRequest
	(*GetSubscriptionRequest)(nil),         // 12: pubsubproto.GetSubscriptionRequest
	(*GetSubscriptionResponse)(nil),        // 13: pubsubproto.GetSubscriptionResponse
	(*UpdateSubscriptionRequest)(nil),      // 14: pubsubproto.UpdateSubscriptionRequest
	(*UpdateSubscriptionResponse)(nil),     // 15: pubsubproto.UpdateSubscriptionResponse
	(*DeleteSubscriptionRequest)(nil),      // 16: pubsubproto.DeleteSubscriptionRequest
	(*ListSubscriptionsRequest)(nil),       // 17: pubsubproto.ListSubscriptionsRequest
	(*ListSubscriptionsResponse)(nil),      // 18: pubsubproto.ListSubscriptionsResponse
	(*Message)(nil),                        // 19: pubsubproto.Message
	(*PublishRequest)(nil),                 // 20: pubsubproto.PublishRequest
	(*PublishResponse)(nil),                // 21: pubsubproto.PublishResponse
	(*SubscribeRequest)(nil),               // 22: pubsubproto.SubscribeRequest
	(*AcknowledgeRequest)(nil),             // 23: pubsubproto.AcknowledgeRequest
	(*ExtendVisibilityTimeoutRequest)(nil), // 24: pubsubproto.ExtendVisibilityTimeoutRequest
	(*GetMessagesInQueueRequest)(nil),      // 25: pubsubproto.GetMessagesInQueueRequest
	(*GetMessagesInQueueResponse)(nil),     // 26: pubsubproto.GetMessagesInQueueResponse
	(*InQueue)(nil),                        // 27: pubsubproto.InQueue
	(*RequeueMessageRequest)(nil),          // 28: pubsubproto.RequeueMessageRequest
	(*PurgeTopicRequest)(nil),              // 29: pubsubproto.PurgeTopicRequest
	(*PurgeTopicResponse)(nil),             // 30: pubsubproto.PurgeTopicResponse
	(*HashDetails)(nil),                    // 31: pubsubproto.HashDetails
	(*ListHashResponse)(nil),               // 32: pubsubproto.ListHashResponse
	nil,                                    // 33: pubsubproto.Message.AttributesEntry
	nil,                                    // 34: pubsubproto.PublishRequest.AttributesEntry
	(*emptypb.Empty)(nil),                  // 35: google.protobuf.Empty
}
var file_v1_pubsub_proto_depIdxs = []int32{
	0,  // 0: pubsubproto.GetTopicResponse.topic:type_name -> pubsubproto.Topic
	0,  // 1: pubsubproto.UpdateTopicResponse.topic:type_name -> pubsubproto.Topic
	0,  // 2: pubsubproto.ListTopicsResponse.topics:type_name -> pubsubproto.Topic
	10, // 3: pubsubproto.GetSubscriptionResponse.subscription:type_name -> pubsubproto.Subscription
	10, // 4: pubsubproto.UpdateSubscriptionResponse.subscription:type_name -> pubsubproto.Subscription
	10, // 5: pubsubproto.ListSubscriptionsResponse.subscriptions:type_name -> pubsubproto.Subscription
	33, // 6: pubsubproto.Message.attributes:type_name -> pubsubproto.Message.AttributesEntry
	34, // 7: pubsubproto.PublishRequest.attributes:type_name -> pubsubproto.PublishRequest.AttributesEntry
	27, // 8: pubsubproto.GetMessagesInQueueResponse.inQueue:type_name -> pubsubproto.InQueue
	31, // 9: pubsubproto.ListHashResponse.hashes:type_name -> pubsubproto.HashDetails
	1,  // 10: pubsubproto.PubSubService.CreateTopic:input_type -> pubsubproto.CreateTopicRequest
	2,  // 11: pubsubproto.PubSubService.GetTopic:input_type -> pubsubproto.GetTopicRequest
	4,  // 12: pubsubproto.PubSubService.UpdateTopic:input_type -> pubsubproto.UpdateTopicRequest
	6,  // 13: pubsubproto.PubSubService.DeleteTopic:input_type -> pubsubproto.DeleteTopicRequest
	8,  // 14: pubsubproto.PubSubService.ListTopics:input_type -> pubsubproto.ListTopicsRequest
	11, // 15: pubsubproto.PubSubService.CreateSubscription:input_type -> pubsubproto.CreateSubscriptionRequest
	12, // 16: pubsubproto.PubSubService.GetSubscription:input_type -> pubsubproto.GetSubscriptionRequest
	14, // 17: pubsubproto.PubSubService.UpdateSubscription:input_type -> pubsubproto.UpdateSubscriptionRequest
	16, // 18: pubsubproto.PubSubService.DeleteSubscription:input_type -> pubsubproto.DeleteSubscriptionRequest
	17, // 19: pubsubproto.PubSubService.ListSubscriptions:input_type -> pubsubproto.ListSubscriptionsRequest
	20, // 20: pubsubproto.PubSubService.Publish:input_type -> pubsubproto.PublishRequest
	22, // 21: pubsubproto.PubSubService.Subscribe:input_type -> pubsubproto.SubscribeRequest
	23, // 22: pubsubproto.PubSubService.Acknowledge:input_type -> pubsubproto.AcknowledgeRequest
	24, // 23: pubsubproto.PubSubService.ExtendVisibilityTimeout:input_type -> pubsubproto.ExtendVisibilityTimeoutRequest
	25, // 24: pubsubproto.PubSubService.GetMessagesInQueue:input_type -> pubsubproto.GetMessagesInQueueRequest
	28, // 25: pubsubproto.PubSubService.RequeueMessage:input_type -> pubsubproto.RequeueMessageRequest
	29, // 26: pubsubproto.PubSubService.PurgeTopic:input_type -> pubsubproto.PurgeTopicRequest
	35, // 27: pubsubproto.PubSubService.ListHash:input_type -> google.protobuf.Empty
	35, // 28: pubsubproto.PubSubService.CreateTopic:output_type -> google.protobuf.Empty
	3,  // 29: pubsubproto.PubSubService.GetTopic:output_type -> pubsubproto.GetTopicResponse
	5,  // 30: pubsubproto.PubSubService.UpdateTopic:output_type -> pubsubproto.UpdateTopicResponse
	35, // 31: pubsubproto.PubSubService.DeleteTopic:output_type -> google.protobuf.Empty
	9,  // 32: pubsubproto.PubSubService.ListTopics:output_type -> pubsubproto.ListTopicsResponse
	35, // 33: pubsubproto.PubSubService.CreateSubscription:output_type -> google.protobuf.Empty
	13, // 34: pubsubproto.PubSubService.GetSubscription:output_type -> pubsubproto.GetSubscriptionResponse
	15, // 35: pubsubproto.PubSubService.UpdateSubscription:output_type -> pubsubproto.UpdateSubscriptionResponse
	35, // 36: pubsubproto.PubSubService.DeleteSubscription:output_type -> google.protobuf.Empty
	18, // 37: pubsubproto.PubSubService.ListSubscriptions:output_type -> pubsubproto.ListSubscriptionsResponse
	21, // 38: pubsubproto.PubSubService.Publish:output_type -> pubsubproto.PublishResponse
	19, // 39: pubsubproto.PubSubService.Subscribe:output_type -> pubsubproto.Message
	35, // 40: pubsubproto.PubSubService.Acknowledge:output_type -> google.protobuf.Empty
	35, // 41: pubsubproto.PubSubService.ExtendVisibilityTimeout:output_type -> google.protobuf.Empty
	26, // 42: pubsubproto.PubSubService.GetMessagesInQueue:output_type -> pubsubproto.GetMessagesInQueueResponse
	35, // 43: pubsubproto.PubSubService.RequeueMessage:output_type -> google.protobuf.Empty
	30, // 44: pubsubproto.PubSubService.PurgeTopic:output_type -> pubsubproto.PurgeTopicResponse
	32, // 45: pubsubproto.PubSubService.ListHash:output_type -> pubsubproto.ListHashResponse
	28, // [28:46] is the sub-list for method output_type
	10, // [10:28] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1_pubsub_proto_init() }
func file_v1_pubsub_proto_init() {
	if File_v1_pubsub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_pubsub_proto_rawDesc), len(file_v1_pubsub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_pubsub_proto_goTypes,
		DependencyIndexes: file_v1_pubsub_proto_depIdxs,
		MessageInfos:      file_v1_pubsub_proto_msgTypes,
	}.Build()
	File_v1_pubsub_proto = out.File
	file_v1_pubsub_proto_goTypes = nil
	file_v1_pubsub_proto_depIdxs = nil
}
